// "use client";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { ReduxProvider } from "@/redux/provider";
import { AuthLayout } from "@/components/layouts/auth";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <ReduxProvider>
        <AuthLayout>
          <div
            className={`${inter.className} min-h-[calc(100vh-148px)] bg-white `}
          >
            {children}
          </div>
        </AuthLayout>
      </ReduxProvider>
    </html>
  );
}
